import iglooLogo from '@/assets/company/igloo-logo.webp';
import kbsysLogo from '@/assets/company/kbsys-logo.webp';
import macrogenLogo from '@/assets/company/macrogen-logo.webp';
import { Company } from '@/types';

export const COMPANY_LIST: Company[] = [
  {
    title: '마크로젠',
    projects: [
      {
        name: 'GenTok 웹 플랫폼 전면개편 및 운영',
        desc: 'React·TypeScript 기반 재설계 및 개발, 레거시 서비스 마이그레이션',
        serviceLink: 'https://gentok.net',
        members: '팀장 1명, 프론트엔드 3명, 백엔드 3명',
        startDate: '2024.05',
        endDate: '2025.10',
        skills: [
          'React',
          'Typescript',
          'Zustand',
          'TanStack Query',
          'Figma',
          'Axios',
          'Mui',
          'Motion.dev',
          'GitHub',
          'GitLab',
          'AWS',
          'Jira',
          'Confluence',
        ],
        details: [
          '기존 레거시 웹 서비스의 운영 및 개선과 TypeScript 기반 신규 서비스 개발을 병행하며 서비스 마이그레이션 수행 (2024.12~2025.03)',
          'B2B 프로모션(네고왕, 현대건설, 롯데카드 등) 이벤트 기능(쿠폰 발행·적용, 분석 상품 장바구니 등) 개발',
          'React Native 웹뷰용 usePermissions 커스텀 훅을 개발하여 카메라·미디어 권한 관리 통합',
          '검증 환경 전용 개발자 모드를 도입하여 테스트 효율 향상',
          'React Router v6 기반 동적 라우팅 및 Vite Rollup manualChunks 설정으로 초기 로딩속도 20% 이상 개선',
          'E-Commerce 구매 흐름(결제·주문·배송·쿠폰 등) 페이지 및 주요 기능 개발',
          '삼성헬스 서비스 연계 및 분석 상태 전달 기능 개발 (25.09 삼성헬스 앱 내 서비스카드 오픈)',
        ],
      },
      {
        name: 'GenTok 앱 전면개편 및 운영 (Android, iOS)',
        desc: 'ReactNative Expo를 이용한 하이브리드 앱 개발 및 운영',
        members: '팀장 1명, 프론트엔드 3명, 백엔드 3명',
        startDate: '2024.07',
        endDate: '2025.10',
        skills: [
          'React',
          'Typescript',
          'Zustand',
          'TanStack Query',
          'Figma',
          'Axios',
          'Mui',
          'Motion.dev',
          'GitHub',
          'GitLab',
          'AWS',
          'Jira',
          'Confluence',
        ],
        details: [
          '레거시 React Native 앱의 빌드 실패 문제(성공률 2% 미만)를 근본적으로 해결하기 위해 신규 앱 아키텍처를 설계·구축하고 서비스 마이그레이션 수행',
          'Firebase Cloud Messaging v1 API로 마이그레이션',
          'React Native와 웹 간 중복 JWT 관리 로직을 통합·제거하여 인증 관련 고객 문의를 90% 감소시키고 자동 로그인 안정화로 UX 개선',
          'TypeScript 인터페이스 기반 메시지 브릿지 훅 개발',
          '소셜 간편 로그인(Naver, Kakao, Google, Apple) 및 삼성헬스 SDK 연동 POC 진행',
          'Firebase DynamicLink 서비스 종료에 대응하여 자체 딥링크 서버를 구축 및 연동',
        ],
      },
    ],
    logo: macrogenLogo,
  },
  {
    title: '이글루코퍼레이션',
    projects: [
      {
        name: '보안관제 통합 솔루션 ExD 개발',
        desc: '신규 보안관제 솔루션 공통 컴포넌트 및 대시보드 개발',
        serviceLink: 'https://gentok.net',
        members: '팀장 1명, 프론트엔드 5명명',
        startDate: '2024.01',
        endDate: '2024.05',
        skills: [
          'React',
          'Typescript',
          'Recoil',
          'Storybook',
          'Figma',
          'Playwright',
          'Axios',
          'GitLab',
          'Jira',
          'Confluence',
        ],
        details: [
          '통합 대시보드 페이지 히스토그램 차트 등 컴포넌트 개발',
          '공통 UI 컴포넌트 개발',
          'Storybook POC 개발',
        ],
      },
      {
        name: '보안관제 AI 솔루션 개발 및 운영',
        desc: 'AI 솔루션 프론트엔드 개발 및 외부 이슈대응 등',
        members: 'PO 1명, 프론트엔드 2명 +  백엔드 2명',
        startDate: '2022.10',
        endDate: '2024.05',
        skills: ['React', 'Typescript', 'Redux', 'Axios', 'GitLab', 'Jira', 'Confluence'],
        details: [
          ' jQuery 기반 DOM 조작 코드를 React 컴포넌트 구조로 개선하여 코드 일관성과 유지 보수성 개선',
          '기존 any 타입 중심의 비정형 코드 구조를 수정, 명확한 타입 정의를 적용하여, 타입 추론 정확도 개선',
          '솔루션 유지보수 및 외부 이슈 대응',
        ],
      },
    ],
    logo: iglooLogo,
  },
  {
    title: '클러쉬 (구 케이비시스)',
    projects: [
      {
        name: 'SK hynix  - Cube 2.0',
        desc: '큐브(사내 메신저) 시스템 고도화 및 신규 기능 추가개발',
        serviceLink: 'https://gentok.net',
        members: 'PM 1명, 웹 개발자 4명명',
        startDate: '2021.08',
        endDate: '2022.04',
        skills: [
          'React',
          'Redux',
          'Redux-Saga',
          'Axios',
          'Ant Design',
          'GitLab',
          'Spring',
          'Oracle DB',
          'Redis',
        ],
        details: [
          '사용자 증가와 Bot을 통한 대용량 트래픽 발생으로 메세지 발송지연이 발생되어 MQ 서버 분리 지원',
          '예약 메세지 기능 구현을 위한 API 개발',
          '메신저 채널 레벨링을 위한 구조 개선 개발을 위한 구조 설계 및 마이그레이션, 프론트엔드 개발',
          '메세지 통합 검색 및 개인환경설정 React 컴포넌트 개발',
        ],
      },
      {
        name: 'Magnachip 반도체 - 구 레거시 교체',
        desc: '노후화된 사내 관리 시스템 신규 개발 및 서비스 마이그레이션션',
        members: 'PM 1명, 웹 개발자 5명',
        startDate: '2020.04',
        endDate: '2021.07',
        skills: [
          'React',
          'Redux',
          'Redux-Saga',
          'Axios',
          'Ant Design',
          'GitLab',
          'Spring',
          'PostgreSQL',
          'Redis',
        ],
        details: [
          'ESH(산업안전보건), GCS(가스캐미컬시스템) 등 관리 페이지 및 API 개발',
          'Jasper Report API 서버 개발  및  리포트 페이지 연동',
          '고객 요청에 따라 식단 등록을 일괄로 진행할 수 있도록 식단 엑셀 업로드 기능 개발',
          '2021년 4월 서비스 오픈 후, 서비스 운영 지원',
        ],
      },
      {
        name: 'SK hynix - Infinity Dashboard 구축',
        desc: '지식블로그(Iflow) 신규 기능 개발 등',
        members: 'PM 1명, 웹 개발자 3명',
        startDate: '2019.11',
        endDate: '2020.03',
        skills: [
          'React',
          'Redux',
          'Redux-Saga',
          'Axios',
          'Ant Design',
          'GitLab',
          'Spring',
          'Oracle DB',
          'Redis',
        ],
        details: [
          'API 중복 호출 등, 라이프사이클  최적화를 통해 렌더링 속도 20% 이상 개선',
          'SNS 형태 페이지의 콘텐츠(텍스트, 이미지, 동영상 등)에 따른 가변 뷰 컴포넌트 개발',
          '게시물 팔로우 기능 API  및 React 컴포넌트 개발',
        ],
      },
    ],
    logo: kbsysLogo,
  },
];
