import { ProjectDetail } from '@/types';

export const PROJECT_LIST: ProjectDetail[] = [
  {
    name: 'GenTok 웹 플랫폼 전면개편 및 운영',
    desc: 'React·TypeScript 기반으로 재설계 및 개발, 레거시 서비스 마이그레이션',
    serviceLink: 'https://gentok.net',
    members: '팀장 1명, 프론트엔드 3명, 백엔드 3명',
    startDate: '2024.05',
    endDate: '2025.10',
    skills: [
      'React',
      'Typescript',
      'Zustand',
      'TanStack Query',
      'Figma',
      'Axios',
      'Mui',
      'Motion.dev',
      'GitHub',
      'GitLab',
      'AWS',
      'Jira',
      'Confluence',
    ],
    details: [
      '기존 레거시 웹 서비스의 운영 및 개선과 TypeScript 기반 신규 서비스 개발을 병행하며 서비스 마이그레이션 수행 (2024.12~2025.03)',
      'B2B 프로모션(네고왕, 현대건설, 롯데카드 등) 이벤트 기능(쿠폰 발행·적용, 분석 상품 장바구니 등) 개발',
      'React Native 웹뷰용 usePermissions 커스텀 훅을 개발하여 카메라·미디어 권한 관리 통합',
      '검증 환경 전용 개발자 모드를 도입하여 테스트 효율 향상',
      'React Router v6 기반 동적 라우팅 및 Vite Rollup manualChunks 설정으로 초기 로딩속도 20% 이상 개선',
      'E-Commerce 구매 흐름(결제·주문·배송·쿠폰 등) 페이지 및 주요 기능 개발',
      '삼성헬스 서비스 연계 및 분석 상태 전달 기능 개발 (25.09 삼성헬스 앱 내 서비스카드 오픈)',
    ],
  },
  {
    name: 'GenTok 앱 전면개편 및 운영 (Android, iOS)',
    desc: 'ReactNative Expo를 이용한 하이브리드 앱 개발 및 운영',
    members: '팀장 1명, 프론트엔드 3명, 백엔드 3명',
    startDate: '2024.07',
    endDate: '2025.10',
    skills: [
      'React',
      'Typescript',
      'Zustand',
      'TanStack Query',
      'Figma',
      'Axios',
      'Mui',
      'Motion.dev',
      'GitHub',
      'GitLab',
      'AWS',
      'Jira',
      'Confluence',
    ],
    details: [
      '레거시 React Native 앱의 빌드 실패 문제(성공률 2% 미만)를 근본적으로 해결하기 위해 신규 앱 아키텍처를 설계·구축하고 서비스 마이그레이션 수행',
      'Firebase Cloud Messaging v1 API로 마이그레이션',
      'React Native와 웹 간 중복 JWT 관리 로직을 통합·제거하여 인증 관련 고객 문의를 90% 감소시키고 자동 로그인 안정화로 UX 개선',
      'TypeScript 인터페이스 기반 메시지 브릿지 훅 개발',
      '소셜 간편 로그인(Naver, Kakao, Google, Apple) 및 삼성헬스 SDK 연동 POC 진행',
      'Firebase DynamicLink 서비스 종료에 대응하여 자체 딥링크 서버를 구축 및 연동',
    ],
  },
];
